- hosts: elasticsearch_master_nodes
  roles:
    - { role: elasticsearch, es_instance_name: "node",
    es_config: {
        cluster.name: "test-cluster",
        discovery.zen.ping.unicast.hosts: "node01, node02, node03", 
        network.host: "_tun0_, _local_",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: false,
        node.master: true,
        bootstrap.memory_lock: true,
        discovery.zen.minimum_master_nodes: 2,
        gateway.recover_after_nodes: 2,
        action.destructive_requires_name: true,
        indices.breaker.total.limit: 70%,
        indices.breaker.fielddata.limit: 25%,
        indices.breaker.request.limit: 40%,
        indices.fielddata.cache.size: 20%,
        indices.queries.cache.size: 40%,
        indices.memory.index_buffer_size: 10%
        }
    }
  vars:
    es_templates: false
    es_scripts: true
    es_java_install: true
    es_major_version: "5.x"
    es_version: "5.2.2"
    es_heap_size: "2g"
    es_api_port: 9200
    es_max_map_count: 262144
    es_max_open_files: 512000   

- hosts: elasticsearch_master_data_nodes
  roles:
    - { role: elasticsearch, es_instance_name: "node",
    es_config: {
        cluster.name: "test-cluster",
        discovery.zen.ping.unicast.hosts: "node01, node02, node03", 
        network.host: "_tun0_, _local_",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: true,
        node.master: true,
        bootstrap.memory_lock: true,
        discovery.zen.minimum_master_nodes: 2,
        gateway.recover_after_nodes: 2,
        action.destructive_requires_name: true,
        indices.breaker.total.limit: 70%,
        indices.breaker.fielddata.limit: 25%,
        indices.breaker.request.limit: 40%,
        indices.fielddata.cache.size: 20%,
        indices.queries.cache.size: 40%,
        indices.memory.index_buffer_size: 10%
        } 
    }
  vars:
    es_java_install: true
    es_major_version: "5.x"
    es_version: "5.2.2"
    es_heap_size: "2g"
    es_plugins_reinstall: true
    es_plugins:
      - plugin: ingest-attachment

- hosts: elasticsearch_client_nodes
  roles:
    - { role: elasticsearch, es_instance_name: "node",
    es_config: {
        cluster.name: "test-cluster",
        discovery.zen.ping.unicast.hosts: "node01, node02, node03", 
        network.host: "_tun0_, _local_",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: false,
        node.master: false,
        bootstrap.memory_lock: true,
        discovery.zen.minimum_master_nodes: 2,
        gateway.recover_after_nodes: 2,
        action.destructive_requires_name: true,
        indices.breaker.total.limit: 70%,
        indices.breaker.fielddata.limit: 25%,
        indices.breaker.request.limit: 40%,
        indices.fielddata.cache.size: 20%,
        indices.queries.cache.size: 40%,
        indices.memory.index_buffer_size: 10%
        } 
    }
  vars:
    es_templates: false
    es_scripts: true
    es_java_install: true
    es_major_version: "5.x"
    es_version: "5.2.2"
    es_heap_size: "2g"
    es_api_port: 9200
    es_max_map_count: 262144
    es_max_open_files: 512000  
    es_plugins_reinstall: true
    es_plugins:
      - plugin: medcl/elasticsearch-analysis-ik
